use crate::lexer::{Lexer,Token,TokenType};
#[derive(Debug,Clone,PartialEq)]
pub enum Expr{Number(i64),Float(f64),String(String),Bool(bool),Null,Identifier(String),Binary{left:Box<Expr>,op:TokenType,right:Box<Expr>},Let{is_secure:bool,is_const:bool,name:String,value:Box<Expr>},Print{expr:Box<Expr>},If{condition:Box<Expr>,then_branch:Vec<Expr>,else_branch:Option<Vec<Expr>>},Repeat{times:Box<Expr>,body:Vec<Expr>},FnDef{name:String,params:Vec<String>,param_types:Vec<Option<String>>,return_type:Option<String>,body:Vec<Expr>},Call{name:String,args:Vec<Expr>},Return{value:Option<Box<Expr>>},NetworkScan{subnet:Box<Expr>},Import{path:String,alias:Option<String>},Export{item:Box<Expr>}}
pub struct Parser<'a>{lexer:Lexer<'a>,current_token:Token}
impl<'a> Parser<'a>{
 pub fn new(lexer:Lexer<'a>)->Self{let mut p=Self{lexer,current_token:Token{kind:TokenType::Eof,line:1,column:1}};p.advance();p}
 pub fn parse(&mut self)->Vec<Expr>{let mut s=Vec::new();while self.current_token.kind!=TokenType::Eof{if self.current_token.kind==TokenType::Semi{self.advance();continue}s.push(self.statement())}s}
 fn statement(&mut self)->Expr{match self.current_token.kind{TokenType::SecureLet=>self.let_stmt(false),TokenType::SecureConst=>self.let_stmt(true),TokenType::Print=>self.print_stmt(),TokenType::If=>self.if_stmt(),TokenType::Repeat=>self.repeat_stmt(),TokenType::Fn=>self.fn_stmt(),TokenType::Return=>self.return_stmt(),TokenType::NetworkScan=>self.scan_stmt(),TokenType::Import=>self.import_stmt(),TokenType::Export=>self.export_stmt(),_=>self.expression()}}
 fn import_stmt(&mut self)->Expr{self.expect(TokenType::Import);let path=match self.current_token.kind.clone(){TokenType::String(s)=>{self.advance();s},TokenType::Identifier(s)=>{self.advance();s},t=>panic!("expected module path after import, found {:?}",t)};let alias=if self.current_token.kind==TokenType::As{self.advance();Some(self.ident("expected alias"))}else{None};Expr::Import{path,alias}}
 fn export_stmt(&mut self)->Expr{self.expect(TokenType::Export);let item=self.statement();Expr::Export{item:Box::new(item)}}
 fn let_stmt(&mut self,c:bool)->Expr{self.advance();let n=self.ident("expected variable name");self.expect(TokenType::Assign);let v=self.expression();Expr::Let{is_secure:true,is_const:c,name:n,value:Box::new(v)}}
 fn print_stmt(&mut self)->Expr{self.expect(TokenType::Print);Expr::Print{expr:Box::new(self.expression())}}
 fn if_stmt(&mut self)->Expr{self.expect(TokenType::If);let c=self.expression();self.expect(TokenType::LBrace);let t=self.block();let e=if self.current_token.kind==TokenType::Else{self.advance();self.expect(TokenType::LBrace);Some(self.block())}else{None};Expr::If{condition:Box::new(c),then_branch:t,else_branch:e}}
 fn repeat_stmt(&mut self)->Expr{self.expect(TokenType::Repeat);let t=self.expression();self.expect(TokenType::LBrace);let b=self.block();Expr::Repeat{times:Box::new(t),body:b}}
 fn fn_stmt(&mut self)->Expr{self.expect(TokenType::Fn);let n=self.ident("expected function name");self.expect(TokenType::LParen);let mut p=Vec::new();let mut pt=Vec::new();while self.current_token.kind!=TokenType::RParen{let name=self.ident("expected parameter");let ty=if self.current_token.kind==TokenType::Colon{self.advance();Some(self.type_name())}else{None};p.push(name);pt.push(ty);if self.current_token.kind==TokenType::Comma{self.advance()}else{break}}self.expect(TokenType::RParen);let rt=if self.current_token.kind==TokenType::Colon{self.advance();Some(self.type_name())}else{None};self.expect(TokenType::LBrace);let b=self.block();Expr::FnDef{name:n,params:p,param_types:pt,return_type:rt,body:b}}
 fn type_name(&mut self)->String{match self.current_token.kind.clone(){TokenType::Identifier(s)=>{self.advance();s.to_lowercase()},t=>panic!("expected type name, found {:?}",t)}}
 fn return_stmt(&mut self)->Expr{self.expect(TokenType::Return);let v=match self.current_token.kind{TokenType::Semi|TokenType::RBrace|TokenType::Eof=>None,_=>Some(Box::new(self.expression()))};Expr::Return{value:v}}
 fn scan_stmt(&mut self)->Expr{self.expect(TokenType::NetworkScan);Expr::NetworkScan{subnet:Box::new(self.expression())}}
 fn block(&mut self)->Vec<Expr>{let mut b=Vec::new();while self.current_token.kind!=TokenType::RBrace&&self.current_token.kind!=TokenType::Eof{if self.current_token.kind==TokenType::Semi{self.advance();continue}b.push(self.statement())}self.expect(TokenType::RBrace);b}
 fn expression(&mut self)->Expr{self.comparison()}
 fn comparison(&mut self)->Expr{let mut l=self.term();while matches!(self.current_token.kind,TokenType::EqualEqual|TokenType::NotEqual|TokenType::Greater|TokenType::Less|TokenType::GreaterEqual|TokenType::LessEqual){let o=self.current_token.kind.clone();self.advance();let r=self.term();l=Expr::Binary{left:Box::new(l),op:o,right:Box::new(r)}}l}
 fn term(&mut self)->Expr{let mut l=self.factor();while matches!(self.current_token.kind,TokenType::Plus|TokenType::Minus){let o=self.current_token.kind.clone();self.advance();let r=self.factor();l=Expr::Binary{left:Box::new(l),op:o,right:Box::new(r)}}l}
 fn factor(&mut self)->Expr{let mut l=self.primary();while matches!(self.current_token.kind,TokenType::Star|TokenType::Slash){let o=self.current_token.kind.clone();self.advance();let r=self.primary();l=Expr::Binary{left:Box::new(l),op:o,right:Box::new(r)}}l}
 fn primary(&mut self)->Expr{match self.current_token.kind.clone(){TokenType::Number(n)=>{self.advance();Expr::Number(n)},TokenType::Float(n)=>{self.advance();Expr::Float(n)},TokenType::String(s)=>{self.advance();Expr::String(s)},TokenType::Identifier(n)=>{self.advance();let name=self.qualified_name(n);match name.to_lowercase().as_str(){"true"=>Expr::Bool(true),"false"=>Expr::Bool(false),"null"=>Expr::Null,_=>{if self.current_token.kind==TokenType::LParen{self.advance();let mut a=Vec::new();while self.current_token.kind!=TokenType::RParen{a.push(self.expression());if self.current_token.kind==TokenType::Comma{self.advance()}else{break}}self.expect(TokenType::RParen);Expr::Call{name,args:a}}else{Expr::Identifier(name)}}}},TokenType::LParen=>{self.advance();let v=self.expression();self.expect(TokenType::RParen);v},t=>panic!("unexpected token {:?} at {}:{}",t,self.current_token.line,self.current_token.column)}}
 fn qualified_name(&mut self,mut name:String)->String{while self.current_token.kind==TokenType::ColonColon{self.advance();name.push_str("::");name.push_str(&self.ident("expected symbol after ::"));}name}
 fn ident(&mut self,msg:&str)->String{match self.current_token.kind.clone(){TokenType::Identifier(n)=>{self.advance();n},t=>panic!("{}: {:?} at {}:{}",msg,t,self.current_token.line,self.current_token.column)}}
 fn expect(&mut self,e:TokenType){if self.current_token.kind!=e{panic!("expected {:?}, found {:?} at {}:{}",e,self.current_token.kind,self.current_token.line,self.current_token.column)}self.advance()}
 fn advance(&mut self){self.current_token=self.lexer.next_token()}
}
